services:
  postgres:
    image: postgres:15-alpine
    container_name: hospital_db
    environment:
      POSTGRES_USER: hospital_db
      POSTGRES_PASSWORD: seguro123
      POSTGRES_DB: hospital_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hospital-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hospital_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: hospital_backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_USER: hospital_db
      DB_PASSWORD: seguro123
      DB_NAME: hospital_db
      DB_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hospital-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: hospital_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - hospital-network
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:

networks:
  hospital-network:
    driver: bridge